- .gitignore
- manifests/database.pp
- manifests/plugin/foreman_gutterball.pp
- manifests/plugin/gutterball.pp
- templates/foreman_gutterball.local.rb.erb
* fixes gutterball installation
* adds foreman_gutterball
> Fixes #8849 - installs foreman_gutterball

- manifests/plugin/foreman_gutterball.pp
depends on https://github.com/Katello/puppet-gutterball/pull/6
> Ref #9134 - foreman-gb plugin sets configs for foreman-gutterball

- manifests/foreman_certs.pp
A follow up to https://github.com/Katello/puppet-certs/pull/61
> Fixes #10097 - Fixed references to city

- manifests/config.pp
- templates/pulp.conf.erb
Refs #13431 - Apache changes for pulp 2.8 Includes updates for pulp.conf
> Refs #13431 - Apache changes for pulp 2.8

- manifests/init.pp
mirrors https://github.com/Katello/puppet-katello/pull/116/
> updates for qpid_client cert module change

- manifests/init.pp
as it should be handled by foreman_proxy_content, that pulls
in crane.
> Remove crane_data_dir

- templates/install_rvm.sh.erb
related to https://github.com/rvm/rvm/issues/4068
> RVM workaround

- manifests/init.pp
- manifests/params.pp
- templates/install_rvm.sh.erb
RVM's stable branch is broken at the time of opening this PR, but the master/head branch works fine.
> Add option to configure rvm branch

- manifests/rvm.pp
- templates/sudoers-dropin.erb
This works around https://bugzilla.redhat.com/show_bug.cgi?id=1483888
> Use a sudoers.d file

- manifests/config.pp
- manifests/database.pp
- manifests/git_repo.pp
- manifests/init.pp
- manifests/rvm_bundle.pp
- manifests/setup.pp
Extracted from https://github.com/theforeman/puppet-katello_devel/pull/96 because I think these are ready to merge already.
> Various cleanups

- manifests/init.pp
- templates/katello.yaml.erb
> Remove pulp oauth

- manifests/init.pp
- manifests/setup.pp
- spec/classes/katello_devel_spec.rb
Both commits aren't really related, but the second commit relies on rewriting the spec file in the first commit.
> Make $github_username really optional & decrease coupling

- manifests/init.pp
- templates/katello.yaml.erb
https://github.com/theforeman/puppet-katello_devel/pull/168
https://github.com/theforeman/puppet-katello/pull/243
https://github.com/Katello/katello/pull/7543
> refs #24070 - add registry to katello.yaml

- templates/env.erb
> Add missing close quote on RAILS_STARTUP command

- manifests/apache.pp
- spec/classes/katello_devel_spec.rb
- templates/env.erb
@stbenjam noticed we serve incorrect certificates in development.
> Use the apache certs

- .fixtures.yml
puppet-pulp switched its squid implementation so we follow suit.
> Correct the puppet-squid fixture

- manifests/bundle.pp
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- manifests/setup.pp
@ekohl Here's my attempt :)
Related to https://github.com/theforeman/forklift/pull/841
> Allow SCL ruby in devel

- manifests/setup.pp
This should improve performance.
> Remove --path vendor from bundle commands

- manifests/bundle.pp
- manifests/init.pp
- manifests/params.pp
- manifests/setup.pp
We are seeing npm install timeout in multiple katello dev environment runs
> Add timeout to npm install

- manifests/params.pp
- spec/classes/katello_devel_spec.rb
To sync with the default Puma settings in https://github.com/theforeman/foreman/pull/7421
> Changed Puma default workers to 2

- manifests/install.pp
educated copy of https://github.com/theforeman/puppet-katello_devel/pull/230 for the `debversion`-extension
> Install postgresql-debversion extension

- manifests/init.pp
Depends on https://github.com/theforeman/puppet-katello/pull/377
> Refs #31693 - Restore katello::qpid_client

- spec/classes/katello_devel_spec.rb
- templates/katello.yaml.erb
Needs https://github.com/theforeman/forklift/pull/1356
> Enable katello agent in devel

- manifests/init.pp
See https://github.com/theforeman/puppet-katello/pull/450
> Drop use of certs::pulp_client

- manifests/init.pp
- spec/acceptance/katello_devel_spec.rb
This is a consequence of work I did here -- https://github.com/theforeman/puppet-katello/commit/b3aed857c63584309043ba5485bdda7b50e3659e
> Set the calculated artemis client DN
