metadata.json
This was 2.x previously, which is no longer correct.
=> Bump puppet-pulp requirement to 3.x

manifests/init.pp
We only call katello::qpid directly, and the katello top-level namespace
isn't loaded when katello_devel is running, so the queue name
doesn't resolve.
=> Specify the candlepin event queue in katello_devel params

templates/_ssl_alias.erb
Fusor frequently receives 503 errors while seeding content post install after starting rails. Even if we wait and watch for a 200 response individual workers can respond with a 503 if the retry timeout isn't 0. 
I've managed to coax 503's out of katello devel installer for capsule registration as well by poking at the https://<fqdn> url repeatedly during install after http is up but before rails is up as well, so it's not entirely specific to fusor.
=> Prevent 503 errors being return by httpd workers

templates/install_rvm.sh.erb
Previously, this would not fill in `$USER` and would end up executing rvm as
root, causing breakages and confusion.
There was a secondary bug where in some cases, `rvm_path` was being set.
However, I think its OK to assume that `install_rvm.sh` is run on a pristine
system, so I left the bugfix out since it may cause confusion if someone really
does want to set `rvm_path`.
=> puppet4 update for `install_rvm.sh`

templates/settings.yaml.erb
This was being referenced improperly for puppet4, resulting in foreman-proxy
not knowing its oauth key/secret in dev installs.
=> add `scope[]` to settings.yml for puppet4

manifests/git_repo.pp
Small thing but there no need to type your username in every time you push if you're using HTTPS
=> Add username in git url

templates/_ssl_alias.erb
Without this, https://github.com/theforeman/foreman/pull/3866 will not work on forklift - the 2 lines here serve the same purpose as the ones for port 3000.
=> Allow storybook to work on forklift

templates/_http.conf.erb
Anaconda cannot get https content, so the route files should be also allowed on regular HTTP, as in a production installation.
=> Allow pulp via HTTP

manifests/plugin.pp, templates/ktest.sh.erb
I've made a few changes to the original `ktest` found https://theforeman.org/plugins/katello/developers.html
This allow you to run it from any directory & using relative paths to test files. e.g
```
[vagrant@centos7-devel test]$ pwd
/home/vagrant/katello/test
[vagrant@centos7-devel test]$ ktest models/content_view_test.rb controllers/api/v2/package_groups_controller_test.rb
``` 
OR
```
[vagrant@centos7-devel models]$ pwd
/home/vagrant/katello/test/models
[vagrant@centos7-devel models]$ ktest content_view_test.rb  -ntest_create
```
=> deploy ktest

manifests/init.pp, manifests/plugin.pp, spec/classes/katello_devel_spec.rb, templates/ktest.sh.erb
This prevents duplicate resource definitions if multiple plugins are used.
Closes GH-110
=> Move ktest to the main class

manifests/database.pp, metadata.json
I was bringing up the centos7-devel image and I was getting this error during the foreman-installer step
`Evaluation Error: Error while evaluating a Resource Statement, Postgresql::Server::Pg_hba_rule[local all]: parameter 'order' expects an Integer value, got String  at /usr/share/katello-installer-base/modules/katello_devel/manifests/database.pp:3
8 on node centos7-devel.example.com`
I was able to fix the problem by changing the 'order' attributes from strings to integers. I also bumped the version of puppetlabs-postgres to be < 6.0.0 from < 5.0.0 which matches puppet-foreman.
=> Bump puppetlabs-postgresql version and fix syntax in database.pp

manifests/init.pp
This parameter was unused and removed.
Fixes GH-123
=> Stop passing in deployment_url to katello::candlepin

manifests/init.pp
qpid_client ensures qpid-cpp-client-devel is installed which the gems need to build.
=> Require qpid_client for installation

manifests/init.pp
The class now has 2 additional parameters which we need to specify. This
copies the defaults.
=> Add missing parameters for katello::qpid

manifests/params.pp, templates/settings.yaml.erb
Mostly motivated by https://github.com/theforeman/foreman/pull/5045, which requires Ruby >= 2.3
To test in forklift:
```yaml
centos7-devel-test:
box: centos7
ansible:
playbook: 'playbooks/devel.yml'
group: 'devel'
variables:
foreman_installer_module_prs: "katello/katello_devel/139"
```
=> Use Ruby 2.4 by default

templates/settings.yaml.erb
To test:
```yaml
centos7-devel-test:
box: centos7
ansible:
playbook: 'playbooks/devel.yml'
group: 'devel'
variables:
foreman_installer_module_prs: "katello/katello_devel/140"
```
=> Use Rails 5 by default in centos7-devel

templates/plugin.local.rb.erb
This allows for plugins like foreman-tasks that have a dash since
it cannot handle:
:foreman-tasks_dev
But can handle:
'foreman-tasks_dev'
=> Bundler group names can't handle dashes with symbols

templates/katello.yaml.erb
The current URL generated is `https://https://foreman_url//api/v2/....`
=> Sync notification URL is wrong

manifests/apache.pp
In https://github.com/theforeman/puppet-katello/pull/241, a file was
converted to a template.
This commit changes the same reference in katello_devel.
=> Fixes #23648 - point to correct template

manifests/apache.pp
To reproduce:
Navigate to https://kat.tello/pub
Katello will now publish both http and https
=> Fixes #24106 - Add /pub to no_proxy_uris

templates/database.yaml.erb
Since Rails 5, it seems the webrick is not limited on single request at
a time, which leads to 500s when loading the dasboards, especially with
plugins.
Suggesting to increse the default pool size in the database.yml
to avoid users running into this.
=> Refs #24220 - increase recommended pool size for the db

manifests/init.pp, manifests/params.pp, templates/env.erb
So @Izhmash encountered a problem with our dev box with provisioning: when Foreman does an SSH finish template on the host it totally locks up the thread and Foreman won't do anything else (including serving the actual provisioning templates to the host).  This changes our devel config to use puma with 5 workers by default.
I noticed a very big speed-up on a lot of pages by using this configuration, as well.
=> Use puma multi-threaded by default in devel

templates/database.yaml.erb
Awhile back, the DB pool size for development was set to 5. This was not enough, and resulted in `ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use)` errors.
The pool size was raised to 10 in https://github.com/theforeman/puppet-katello_devel/pull/165 which helped, but the error would still pop up occasionally when viewing the Katello dashboard.
This commit raises the limit to 20. I have not seen the pool error since raising to 20 on my local environment.
=> Bump DB pool size

templates/ktest.sh.erb
Due to 3784e5bc9f17c38a3cde9bf2c5e458a88398e5da we need `bundler exec` to
run ruby now.
Thanks to @leewaa, @ekohl and @timogoebel for investigation and fixing.
=> Fix ktest single mode

templates/settings.yaml.erb
Turning this off speeds up the development server.
There is very little reason for this flag to be on. UI changes
reload fine with it off. AFAICT the only reason to turn it on
is to debug any of the angular/bastion code in the browser.
=> Turn off assets debug

files/install_rvm.sh
it looks like the gpg keys changed for rvm, we
can update them in our script.
See more info here:
https://rvm.io/integration/vagrant#using-rvm-with-vagrant
=> Update RVM gpg keys

files/install_rvm.sh
I keep hitting this error:
```
[[33m WARN[0m [34m2019-01-30T14:46:30[0m [36mverbose[0m]  /Stage[main]/Katello_devel::Rvm/File[/usr/bin/install_rvm.sh]/ensure: defined content as '{md5}eeb021788a828be784bc317b169ff5a4'
[[32m INFO[0m [34m2019-01-30T14:46:30[0m [36mverbose[0m]  /Stage[main]/Katello_devel::Rvm/File[/usr/bin/install_rvm.sh]: Scheduling refresh of Exec[/usr/bin/install_rvm.sh 2.5 stable]
[[33m WARN[0m [34m2019-01-30T14:47:55[0m [36mverbose[0m]  /Stage[main]/Katello_devel::Rvm/Exec[/usr/bin/install_rvm.sh 2.5 stable]/returns: gpg: directory `/home/vagrant/.gnupg' created
[[33m WARN[0m [34m2019-01-30T14:47:55[0m [36mverbose[0m]  /Stage[main]/Katello_devel::Rvm/Exec[/usr/bin/install_rvm.sh 2.5 stable]/returns: gpg: new configuration file `/home/vagrant/.gnupg/gpg.conf' created …
```
=> Fetch keys from the keyserver suggested by rvm

manifests/init.pp
https://github.com/theforeman/puppet-certs/commit/7d07caccafec2756f63a4ff4648955a7a1b4f670 renamed parameters.
=> Update usage for puppet-certs

manifests/install.pp
This fixes qdrouterd:
```
Apr 12 18:16:50 centos7-devel.jturel.example.com qdrouterd[1770]: 2019-04-12 18:16:50.079540 +0000 SERVER (info) Connection to localhost:5671 failed: amqp:unauthorized-access SASL(-4): no mechanism available: No
worthy mechs found (Authentication failed [mech=none])
```
In relation to: https://github.com/theforeman/puppet-qpid/pull/120
=> Install cyrus-sasl-plain

manifests/init.pp
If rake db:seed is ran before the katello_event_queue bindings are created, Candlepin will be in suspend mode and db:seed will fail. This is breaking the devel box currently
```
2019-05-06 21:41:49,663 [thread=localhost-startStop-1] [=, org=, csid=] INFO  org.candlepin.audit.QpidConnection - AMQP connection factory created.
2019-05-06 21:41:50,611 [thread=localhost-startStop-1] [=, org=, csid=] WARN  org.candlepin.audit.QpidConnection - Closing connection to Qpid since the binding is missing!
2019-05-06 21:41:50,612 [thread=localhost-startStop-1] [=, org=, csid=] INFO  org.candlepin.controller.ModeManagerImpl - Entering new mode SUSPEND for the following reasons: [QPID_MISSING_BINDING]
2019-05-06 21:41:50,612 [thread=localhost-startStop-1] [=, org=, csid=] WARN …
```
=> Make sure Qpid is in place before Candlepin

metadata.json
Since we don't publish this module and don't regularly check the dependencies, this is easier to maintain. We basically need the latest versions of a certain module and if they're incompatible, we need to fix them.
=> Remove upper version bounds

manifests/setup.pp
Reverts theforeman/puppet-katello_devel#196
This doesn't work right now. Probably because the Puppet exec doesn't read `GEM_HOME` when running `bundle install`.
=> Revert "Remove --path vendor from bundle commands"

.fixtures.yml
The pulp module started to use selboolean which requires selinux_core on Puppet 6.
=> Add selinux_core as a test fixture

spec/classes/katello_devel_spec.rb, templates/env.erb
This environment variable will remove redux logging to the browser console. With Devtools extensions
and the ability to easily turn it back on, there isn't a need for this to be turned on by default.
=> Turn off redux logging to console

templates/ktest.sh.erb
ktest doesn't currently run multiple test files. see the assertion counts in before and after below. The ruby executable only accepts a single .rb file, and that can be worked around be requiring each of the test files through `-e`
Still works with a single file ;)
Before:
```
[vagrant@centos7-devel foreman]$ bundle exec ktest ~/katello/test/services/katello/event_daemon_test.rb ~/katello/test/services/katello/event_monitor/poller_thread_test.rb --seed=53467
-- execute("SET CONSTRAINTS ALL DEFERRED;")
-> 0.0007s
Run options: --seed=53467
...
Finished in 0.595936s, 5.0341 runs/s, 10.0682 assertions/s.
3 runs, 6 assertions, 0 failures, 0 errors, 0 skips
```
After
```
[vagrant@centos7-devel foreman]$ bundle exec ktest ~/katello/test/services/katello/event_daemon_test.rb …
```
=> ktest support multiple files

templates/settings.yaml.erb
As a developer, I don't see a lot of need to log auditing and taxonomies in debug mode by default. Also, changing dynflow logging level to info will reduce the noise it creates while still logging errors and important information.
The amount of noise they generate to the value the logs create doesn't seem beneficial to developer productivity. These log levels can be easily be changed when needed
=> Update devel env logging levels

manifests/init.pp
Katello refactored its classes to make them usable for stand alone usage. That means some parameters changed and no longer need to be passed in.
https://github.com/theforeman/puppet-katello/commit/ac38043b74cd6af414a358beddd0c029f9d4dfa8
Fixes #217
=> Change the class structure

manifests/init.pp
Devels can't spin up properly as the rails server which now connects to qpid can't read the certs resulting in a fatal error while registering the smart proxy:
```
2020-01-08T19:22:19 [I|app|7b843db3] Katello event daemon started process=16908
2020-01-08T19:22:19 [I|app|7b843db3] Processing by Api::V2::SmartProxiesController#index as JSON
2020-01-08T19:22:19 [I|app|7b843db3]   Parameters: {"search"=>"name=\"centos7-luna-devel.dhcp-2-154.example.com\"", "apiv"=>"v2", "smart_proxy"=>{}}
terminate called after throwing an instance of 'qpid::types::Exception'
what():  Failed to initialise SSL: Failed: NSS error [-8015] (/builddir/build/BUILD/qpid-cpp-1.39.0/src/qpid/sys/ssl/util.cpp:100) (/builddir/build/BUILD/qpid-cpp-1.39.0/src/qpid/client/SslConnector.cpp:149)
Aborted
```
``` …
```
=> Add Katello user to qpidd group

manifests/init.pp
certs 7.0.0 started to create qpid files owned by the pulp group. This group is created by pulp-server which is in pulp::install. This more specific chaining avoids dependency cycles.
This is an alternative to https://github.com/theforeman/puppet-certs/pull/270. Related to https://github.com/theforeman/puppet-certs/pull/272.
=> katello/certs 7.x compatibility

manifests/database.pp, manifests/init.pp
There is no need for candlepin to be a superuser and the katello::candlepin class can manage it for us
=> Do not make the candlepin user a db superuser

manifests/apache.pp, manifests/init.pp
This module had declared it's own vhost using a similar naming convention and directory structure as Foreman's. This causes a conflict when pulpcore is enabled since pulpcore relies on adding fragments to Foreman's vhost declaration specifically around the use of `05-foreman-ssl.d`. To solve this, and bring greater continuity I have attempted to declare the `foreman::config::apache` class and re-use it here.
=> Use foreman apache configs to unblock Pulp 3

manifests/init.pp, templates/katello.yaml.erb
Katello 3.9 dropped this setting
=> Drop unused post_sync_url

manifests/setup.pp
These groups have been removed and serve no more purpose.
=> Drop --without mysql:mysql2 from bundle

manifests/install.pp
Adds the postgresql-evr extension needed for the upcoming `evt_t` postgresql type.  This won't work out of the box until the package is built in release but it is in staging currently.
=> Add postgresql-evr extension

manifests/init.pp
To test, define a nightly devel box which uses staging repos, and applies this PR and the two related ones:
```
centos7-katello-devel-staging:                                                                                                                                
box: centos7                                                                                                                                                
ansible:                                                                                                                                                    
playbook: 'playbooks/katello_devel.yml'                                                                                                                   
group: 'devel' …
```
=> Override candlepin client cert+key to devel user

templates/katello.yaml.erb
as pulp3 is being used for yum
=> turn katello_applicability on by default

.fixtures.yml, manifests/config.pp, manifests/init.pp, manifests/params.pp, metadata.json, spec/classes/katello_devel_spec.rb, templates/katello.yaml.erb
This follows what was done in puppet-katello and puppet-foreman_proxy_content.
=> Drop Pulp 2 + enable deb support by default

manifests/install.pp
Katello recently started to talk to qpid again to support katello-agent. This needs a devel package to be present.
I should note that I didn't check this myself, but I'm going on the [report in forklift](https://github.com/theforeman/forklift/issues/1288#issuecomment-776605202).
=> Ensure qpid-proton-c-devel is installed

templates/ktest.sh.erb
The warning was:
[DEPRECATED] use `bundle info rake` instead of `bundle show rake`
=> Fix bundler deprecation warning in ktest

manifests/init.pp
Previously this was duplicated. Now they are guaranteed to be in sync.
Fixes: aa27b00a649a47577768609f61e1c5226eb96f18
=> Use variables for SSL paths

manifests/apache.pp, spec/acceptance/hieradata/common.yaml
puppet-katello included this as of
https://github.com/theforeman/puppet-katello/commit/afc08e300edb831d8821cb335a341afbca161cf1
=> include apache::mod::setenvif

manifests/install.pp
The package 'cyrus-sasl-plain' is declared twice for dev box:
https://github.com/theforeman/puppet-katello_devel/blob/master/manifests/install.pp
https://github.com/theforeman/puppet-qpid/blob/master/manifests/install.pp#L21
This throws a duplicate declaration error on vagrant up of katello dev boxes.
=> Remove duplicate declaration of package: cyrus-sasl-plain

manifests/init.pp
Previously this was set to 900 seconds (15 minutes). More recently,
the `npm install` step has been observed to take over 30 minutes.
This was causing failures in local installation as well as in the
CI environment.
=> Increase npm_timeout default to 45 minutes

manifests/apache.pp
In https://github.com/theforeman/puppet-foreman/commit/215db6539dbfdbd2896946537f1e520fac7f63ba we made a change that `/webpack` and `/assets` are served by Apache by default. This is correct for production setups, but breaks development ones, as here `/assets` is actually served by Rails.
Explicitly configure `foreman::apache` to not include these in the "no_proxy" list.
=> Refs #33956 - proxy assets and webpack to Rails in devel

manifests/config.pp, manifests/init.pp, manifests/plugin.pp, spec/classes/katello_devel_spec.rb
This approach allows plugins to be defined optionally by a Hash instead of a String.
This is useful when working with a plugin that differs from the plugin source on github, or if it is not (yet) available on github at all.
It is also provides all the machinery needed in the plugin class to allow for an unmanaged Katello repository, via a trivial follow up commit.
This all can be useful also if the user prefers to manage their source repositories directly in forklift or via any other external approach.
Without this capability, the installer will either overwrite the user's changes or it will fail with an error.
=> Allow plugin source repositories to be unmanaged

manifests/config.pp, spec/classes/katello_devel_spec.rb
Allow specifying an scm-branch for `extra_plugins`.
This will come in handy, if `foreman_scm_revision` and `katello_scm_revision` are specified to a version that requires a non-default-branch version of the `extra_plugins`.
=> Add plugin scm version

.fixtures.yml, manifests/install.pp
This depends on a puppet/rhsm module. Considering this is a bit of an edge case, I put it in as an optional dependency.
=> Use RHEL flavor of CRB on RHEL

.fixtures.yml
This appears needed since https://github.com/theforeman/puppet-dns/commit/3f53f46ee50a5476504e227164680f0bd548c8b6
=> Add puppet-dns to fixtures

templates/plugin.local.rb.erb
[SAT-26017](https://issues.redhat.com/browse/SAT-26017)
This PR exists to mitigate the issues popping up for gem dependencies when running local testing on a katello devel environment. All katello gem dependencies are now added to the foreman bundler.d directory during a full foreman/katello install.
[Previous forklift PR](https://github.com/theforeman/forklift/pull/1835)
1. In forklift, create a new katello-devel environment by modifying your `99-local.yaml` config file.
2. Under ansible -> variables -> foreman_installer_module_prs, add the following line: `- theforeman/katello_devel/305` [[Documentation]](https://theforeman.github.io/forklift/development/#test-puppet-module)
3. Create and provision the environment. Beyond normal foreman install issues, everything should go smoothly. The …
=> Evaluate plugin gemfiles during bundle operations

manifests/init.pp, manifests/setup.pp, spec/classes/katello_devel_spec.rb, templates/env.erb, templates/settings.yaml.erb
for https://github.com/theforeman/foreman/pull/9834
=> Remove webpack server settings

manifests/setup.pp
For some reason this seems to depend on db being migrated, currently the webpack compile step fails like this https://gist.github.com/lumarel/3d04de883cc14deb7f5cff12b0ea2e30 .
Afaik it shouldn't be necessary anymore, if foreman is started with the provided procfile, webpack should be watching the directory and compiling assets on the fly.
An alternative fix would be to change the ordering.
=> Drop rake webpack:compile
